version: '2'

# We're going to rely on an externally created network for our services to get around the 
# problem with docker compose using underscores in network and container names (and thus causing
# problems with invalid hostnames). See the comment on 34e78d05af2a287030598e545341ada36e9d24c 
# for more details. You can create this network by running: 'docker network create graph'
networks:
  graph:
    external: true

services:
  # One DSE node
  dse:
    image: luketillman/datastax-enterprise:5.1.0
    # Tell DSE to start a graph node
    command: [ -g ]
    cap_add:
    - IPC_LOCK
    ulimits:
      memlock: -1
    # Use the externally created network (see note above)
    networks:
    - graph
    # Specify the container name explicitly to avoid getting underscores (see note above)
    container_name: dse

  # One instance of DataStax Studio
  studio:
    image: luketillman/datastax-studio:2.0.0
    ports:
    # The Web UI exposed to our host
    - "9091:9091"
    depends_on:
    - dse
    # Use the externally created network (see note above)
    networks:
    - graph